// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/db.go

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/rvarbanov/mini-scan-takehome/internal/model"
)

// MockDBInterface is a mock of DBInterface interface.
type MockDBInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDBInterfaceMockRecorder
}

// MockDBInterfaceMockRecorder is the mock recorder for MockDBInterface.
type MockDBInterfaceMockRecorder struct {
	mock *MockDBInterface
}

// NewMockDBInterface creates a new mock instance.
func NewMockDBInterface(ctrl *gomock.Controller) *MockDBInterface {
	mock := &MockDBInterface{ctrl: ctrl}
	mock.recorder = &MockDBInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBInterface) EXPECT() *MockDBInterfaceMockRecorder {
	return m.recorder
}

// StoreScan mocks base method.
func (m *MockDBInterface) StoreScan(ctx context.Context, scan model.Scan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreScan", ctx, scan)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreScan indicates an expected call of StoreScan.
func (mr *MockDBInterfaceMockRecorder) StoreScan(ctx, scan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreScan", reflect.TypeOf((*MockDBInterface)(nil).StoreScan), ctx, scan)
}
